import { useEffect, useState } from 'react'
import { AnimatePresence, motion as Motion } from 'framer-motion'

const Icon = ({ name, size = 20, stroke = 1.8 }) => {
  const paths = {
    palette: <><path d="M12 3a9 9 0 0 0 0 18h1.2a1.8 1.8 0 0 0 1.2-3.1 1.8 1.8 0 0 1 1.2-3.1H18A3 3 0 0 0 21 12c0-5-4-9-9-9Z" /><circle cx="7.5" cy="11" r="1" /><circle cx="10" cy="7.5" r="1" /><circle cx="15" cy="7.5" r="1" /></>,
    sparkles: <><path d="m12 3 1.1 4.9L18 9l-4.9 1.1L12 15l-1.1-4.9L6 9l4.9-1.1L12 3Z" /><path d="m19 15 .6 2.4L22 18l-2.4.6L19 21l-.6-2.4L16 18l2.4-.6L19 15Z" /></>,
    heart: <path d="M20.8 8.8c0 5.1-8.8 10.1-8.8 10.1S3.2 13.9 3.2 8.8A4.5 4.5 0 0 1 12 6.6a4.5 4.5 0 0 1 8.8 2.2Z" />,
    info: <><circle cx="12" cy="12" r="9" /><path d="M12 11v5M12 8h.01" /></>, plus: <><path d="M12 5v14M5 12h14" /></>,
    refresh: <><path d="M20 11a8 8 0 0 0-14.7-4L4 9" /><path d="M4 4v5h5M4 13a8 8 0 0 0 14.7 4L20 15" /><path d="M20 20v-5h-5" /></>,
    copy: <><rect x="8" y="8" width="11" height="11" rx="2" /><path d="M16 8V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2" /></>, x: <><path d="m6 6 12 12M18 6 6 18" /></>,
    trash: <><path d="M5 7h14M10 11v6M14 11v6M9 7V4h6v3m-9 0 1 13h10l1-13" /></>, arrow: <><path d="M5 12h13M13 7l5 5-5 5" /></>,
  }
  return <svg aria-hidden="true" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={stroke} strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>
}

function App() {
  const hslToHex = (h, s, l) => { l /= 100; const a = s * Math.min(l, 1 - l) / 100; const f = n => { const k = (n + h / 30) % 12; const color = l - a * Math.max(Math.min(k - 3, 9 - k, 1), -1); return Math.round(255 * color).toString(16).padStart(2, '0') }; return `#${f(0)}${f(8)}${f(4)}` }
  const generateComplementaryPalette = () => { const hue = Math.floor(Math.random() * 360); const sat = 60 + Math.floor(Math.random() * 30); return [hslToHex(hue, sat, 50), hslToHex((hue + 30) % 360, sat, 55), hslToHex((hue + 180) % 360, sat, 50), hslToHex((hue + 210) % 360, sat, 55), hslToHex((hue + 150) % 360, sat - 10, 60)] }
  const [colors, setColors] = useState(() => generateComplementaryPalette()); const [copyStatus, setCopyStatus] = useState(null); const [view, setView] = useState('generator'); const [favorites, setFavorites] = useState(() => JSON.parse(localStorage.getItem('myPalettes')) || [])
  useEffect(() => localStorage.setItem('myPalettes', JSON.stringify(favorites)), [favorites])
  const addColor = () => { if (colors.length < 5) { const hue = parseInt(colors[colors.length - 1].slice(1), 16); setColors([...colors, hslToHex((hue % 360 + 60) % 360, 70, 55)]) } }
  const removeColor = index => { if (colors.length > 2) setColors(colors.filter((_, i) => i !== index)) }; const copyToClipboard = hex => { navigator.clipboard.writeText(hex); setCopyStatus(hex); setTimeout(() => setCopyStatus(null), 2000) }; const saveToFavorites = () => { if (!favorites.some(p => JSON.stringify(p) === JSON.stringify(colors))) setFavorites([...favorites, [...colors]]) }; const removeFavorite = index => setFavorites(favorites.filter((_, i) => i !== index))
  const navItems = [{ id: 'generator', label: 'Explorar', icon: 'sparkles' }, { id: 'favorites', label: 'Mis paletas', icon: 'heart', count: favorites.length }]
  return <div className="app-shell"><aside className="sidebar"><button className="brand" onClick={() => setView('generator')} aria-label="Ir al generador"><span className="brand-mark"><Icon name="palette" size={23} /></span><span><strong>Color</strong> Theme</span></button><div className="sidebar-label">Biblioteca</div><nav className="side-nav" aria-label="Navegación principal">{navItems.map(item => <button key={item.id} onClick={() => setView(item.id)} className={view === item.id ? 'nav-item active' : 'nav-item'} aria-current={view === item.id ? 'page' : undefined}><Icon name={item.icon} /><span>{item.label}</span>{item.count > 0 && <span className="nav-count">{item.count}</span>}</button>)}</nav><div className="sidebar-spacer" /><button onClick={() => setView('policies')} className={view === 'policies' ? 'nav-item active' : 'nav-item'}><Icon name="info" /><span>Acerca de</span></button><div className="sidebar-footer"><span className="status-dot" /> Guardado localmente</div></aside>
    <main className="main-content"><header className="topbar"><div><p className="eyebrow">Color Theme</p><h1>{view === 'generator' ? 'Generador de paletas' : view === 'favorites' ? 'Mis paletas' : 'Acerca de'}</h1></div><div className="topbar-actions"><span className="keyboard-hint">⌘ K</span><button className="icon-button" onClick={() => setView('policies')} aria-label="Información"><Icon name="info" /></button></div></header><AnimatePresence mode="wait">
      {view === 'generator' && <Motion.section key="generator" className="view generator-view" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }}><div className="section-intro"><div><h2>Encuentra tu combinación</h2><p>Genera una paleta armónica para tu próximo proyecto.</p></div><button className="save-button" onClick={saveToFavorites}><Icon name="heart" size={17} /> Guardar paleta</button></div><div className="palette-card" aria-label="Paleta actual">{colors.map((color, index) => <Motion.div key={color} layout className="color-column" style={{ backgroundColor: color }} initial={{ opacity: 0, scale: .98 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: .94 }}><button className="color-code" onClick={() => copyToClipboard(color)} aria-label={`Copiar color ${color}`}><span className="copy-icon"><Icon name="copy" size={15} /></span>{color.toUpperCase()}</button>{colors.length > 2 && <button className="remove-color" onClick={() => removeColor(index)} aria-label={`Eliminar color ${color}`}><Icon name="x" size={16} /></button>}</Motion.div>)}</div><div className="palette-meta"><span><span className="meta-dot" style={{ backgroundColor: colors[0] }} /> Paleta complementaria</span><span>{colors.length} colores · Haz clic en un código para copiar</span></div><div className="generator-actions"><button className="secondary-button" onClick={addColor} disabled={colors.length >= 5}><Icon name="plus" size={18} /> Añadir color</button><button className="primary-button" onClick={() => setColors(generateComplementaryPalette())}><Icon name="refresh" size={18} /> Generar nueva</button></div></Motion.section>}
      {view === 'favorites' && <Motion.section key="favorites" className="view" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }}><div className="section-intro"><div><h2>Tus paletas guardadas</h2><p>Vuelve a tus combinaciones favoritas cuando quieras.</p></div><span className="count-badge">{favorites.length} {favorites.length === 1 ? 'paleta' : 'paletas'}</span></div>{favorites.length === 0 ? <div className="empty-state"><span className="empty-icon"><Icon name="heart" size={28} /></span><h3>Aún no hay paletas</h3><p>Guarda una paleta desde el generador para verla aquí.</p><button className="primary-button" onClick={() => setView('generator')}><Icon name="arrow" size={18} /> Ir al generador</button></div> : <div className="favorites-grid">{favorites.map((pal, pIdx) => <article key={pIdx} className="favorite-card"><div className="favorite-swatches">{pal.map((c, cIdx) => <div key={cIdx} style={{ backgroundColor: c }} />)}</div><div className="favorite-info"><div><strong>Paleta {String(pIdx + 1).padStart(2, '0')}</strong><span>{pal.length} colores</span></div><div className="card-actions"><button onClick={() => { setColors(pal); setView('generator') }} aria-label={`Cargar paleta ${pIdx + 1}`}><Icon name="arrow" size={17} /></button><button onClick={() => removeFavorite(pIdx)} aria-label={`Eliminar paleta ${pIdx + 1}`}><Icon name="trash" size={17} /></button></div></div></article>)}</div>}</Motion.section>}
      {view === 'policies' && <Motion.section key="policies" className="view about-card" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }}><span className="about-icon"><Icon name="palette" size={30} /></span><h2>Color Theme</h2><p>Una herramienta sencilla para crear paletas de color armónicas. Tus paletas favoritas se guardan localmente en este navegador mediante LocalStorage.</p><button className="secondary-button" onClick={() => setView('generator')}><Icon name="arrow" size={18} /> Volver al generador</button></Motion.section>}
    </AnimatePresence><footer><span>© 2026 Color Theme</span><a href="https://github.com/NotExer">GitHub <Icon name="arrow" size={14} /></a></footer></main><AnimatePresence>{copyStatus && <Motion.div className="toast" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 12 }}><span className="toast-color" style={{ backgroundColor: copyStatus }} /><span><strong>{copyStatus.toUpperCase()}</strong> copiado al portapapeles</span><Icon name="copy" size={16} /></Motion.div>}</AnimatePresence></div>
}
export default App
